name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/vue-test:latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up jq (for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set lowercase image tag
        run: |
          echo "IMAGE_TAG_LOWER=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Extract Node version from package.json
        id: node_version
        run: |
          NODE_VERSION=$(jq -r '.engines.node' package.json | sed 's/x$/0/')
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG_LOWER }}
          build-args: |
            NODE_VERSION=${{ steps.node_version.outputs.node_version }}
